x-logging: &logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  server-init:
    image: alpine:latest
    networks:
      - nym_network
    volumes:
      - server_data:/app/storage
    command: |
      sh -c '
        mkdir -p /app/storage
        echo "your_secure_password" > /app/storage/encryption_password.txt && 
        chmod 600 /app/storage/encryption_password.txt
      '

  server:
    build:
      context: ./server
    restart: unless-stopped
    depends_on:
      - server-init
    networks:
      - nym_network
    volumes:
      - address_data:/app/shared  # Single shared volume for communication
      - server_data:/app/storage
      - server_nym_data:/root/.nym  # Renamed for consistency
    environment:
      - SECRET_PATH=/app/storage/encryption_password.txt
      - NYM_CLIENT_ID=nym_server
    ports:
      - "1977:1977"
    logging: *logging
    healthcheck:
      test: "cat /app/shared/nym_address.txt | grep '@' || exit 1" # Ensure the file is not just empty
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 40s

  client:
    build: ./client
    restart: unless-stopped
    depends_on:
      server:
        condition: service_healthy
    networks:
      - nym_network
    volumes:
      - address_data:/app/shared:ro  # Use the same shared volume
      - client_data:/app/storage
      - client_nym_data:/root/.nym
    ports: 
      - "8080:8080"
    command: >
      sh -c '
        echo "Waiting for the server to fully initialize..."
        while [ ! -s /app/shared/nym_address.txt ] || ! grep -q "@" /app/shared/nym_address.txt; do
          echo "Server is not fully ready, waiting..."
          sleep 2
        done

        # Ensure .env is properly updated
        rm -f /app/.env  # Remove old .env
        cp /app/shared/nym_address.txt /app/.env
        sed -i 's/^/SERVER_ADDRESS=/' /app/.env
        echo "Updated .env file content:"
        cat /app/.env  # Print for debugging

        # Run the client application
        exec python src/runClient.py
      '
    logging: *logging

networks:
  nym_network:
    driver: bridge

volumes:
  server_data:
  server_nym_data:  # Updated to match client format
  client_data:
  client_nym_data:
  address_data:  # Single shared volume
