
x-logging: &logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  server-init:
    image: alpine:latest
    networks:
      - nym_network
    volumes:
      - server_data:/app/storage
    command: |
      sh -c '
        mkdir -p /app/storage
        echo "your_secure_password" > /app/storage/encryption_password.txt && 
        chmod 600 /app/storage/encryption_password.txt
      '
  server:
    build:
      context: ./server/
    restart: unless-stopped
    depends_on:
      - server-init
    networks:
      - nym_network
    volumes:
      - shared_data:/app/shared
      - server_data:/app/storage
      - nym_client_data:/root/.nym
      - address_data:/app/shared  # CRITICAL: Shared volume with fixed path
    environment:
      - SECRET_PATH=/app/storage/encryption_password.txt
      - NYM_CLIENT_ID=nym_server
    ports:
      - "1977:1977"
    logging: *logging
    healthcheck:
      test: test -f /app/shared/nym_address.txt
      interval: 5s
      timeout: 5s
      retries: 12
      start_period: 10s
      
  client:
    build: ./client
    restart: unless-stopped
    depends_on:
      server:
        condition: service_healthy
    networks:
      - nym_network
    volumes:
      - shared_data:/app/shared:ro
      - client_data:/app/storage
      - client_nym_data:/root/.nym
      - address_data:/app/shared:ro  # CRITICAL: Same mount point as server
    ports: 
      - "8080:8080"
    command: |
      sh -c '
        while [ ! -s /app/shared/nym_address.txt ]; do
          echo "Waiting for valid server address..."
          sleep 2
        done
        
        SERVER_ADDRESS=$(cat /app/shared/nym_address.txt)
        echo "Using SERVER_ADDRESS: $SERVER_ADDRESS"
        export SERVER_ADDRESS
        
        exec python src/runClient.py
      '
    logging: *logging

networks:
  nym_network:
    driver: bridge

volumes:
  server_data:
  shared_data:
  nym_client_data:
  client_data:
  client_nym_data:
  address_data:  # Dedicated volume for address sharing
